"""Add new fields to models for AI analysis

Revision ID: 1111217c5b24
Revises: 95bc0f832711
Create Date: 2025-07-05 01:39:47.302453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1111217c5b24'
down_revision = '95bc0f832711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apscheduler_jobs_next_run_time'))

    op.drop_table('apscheduler_jobs')
    op.drop_table('virtual_accounts')
    op.drop_table('users')
    with op.batch_alter_table('virtual_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_account_time'))
        batch_op.drop_index(batch_op.f('idx_stock_time'))

    op.drop_table('virtual_trades')
    with op.batch_alter_table('virtual_account_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_account_snapshot_time'))

    op.drop_table('virtual_account_snapshots')
    with op.batch_alter_table('virtual_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_account_stock'))

    op.drop_table('virtual_positions')
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('stock_code'))

    op.drop_table('watchlists')
    with op.batch_alter_table('backtest_results', schema=None) as batch_op:
        batch_op.alter_column('ai_analysis_report',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='AI 分析报告',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_results', schema=None) as batch_op:
        batch_op.alter_column('ai_analysis_report',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='AI 分析报告',
               existing_nullable=True)

    op.create_table('watchlists',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stock_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('stock_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('added_at', mysql.DATETIME(), nullable=True),
    sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('alert_price', mysql.FLOAT(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('stock_code'), ['stock_code'], unique=True)

    op.create_table('virtual_positions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stock_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('stock_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avg_cost', mysql.FLOAT(), nullable=False),
    sa.Column('current_price', mysql.FLOAT(), nullable=True),
    sa.Column('market_value', mysql.FLOAT(), nullable=True),
    sa.Column('unrealized_pnl', mysql.FLOAT(), nullable=True),
    sa.Column('unrealized_pnl_rate', mysql.FLOAT(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['virtual_accounts.id'], name=op.f('virtual_positions_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('virtual_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_account_stock'), ['account_id', 'stock_code'], unique=False)

    op.create_table('virtual_account_snapshots',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('snapshot_time', mysql.DATETIME(), nullable=False),
    sa.Column('cash', mysql.FLOAT(), nullable=False),
    sa.Column('market_value', mysql.FLOAT(), nullable=False),
    sa.Column('total_value', mysql.FLOAT(), nullable=False),
    sa.Column('total_return', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['virtual_accounts.id'], name=op.f('virtual_account_snapshots_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('virtual_account_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_account_snapshot_time'), ['account_id', 'snapshot_time'], unique=False)

    op.create_table('virtual_trades',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stock_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('stock_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('trade_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('fee', mysql.FLOAT(), nullable=True),
    sa.Column('cash_after', mysql.FLOAT(), nullable=False),
    sa.Column('trade_time', mysql.DATETIME(), nullable=True),
    sa.Column('strategy_signal', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['virtual_accounts.id'], name=op.f('virtual_trades_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('virtual_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_stock_time'), ['stock_code', 'trade_time'], unique=False)
        batch_op.create_index(batch_op.f('idx_account_time'), ['account_id', 'trade_time'], unique=False)

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('nickname', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('avatar', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('virtual_accounts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('initial_capital', mysql.FLOAT(), nullable=False),
    sa.Column('current_cash', mysql.FLOAT(), nullable=False),
    sa.Column('total_value', mysql.FLOAT(), nullable=False),
    sa.Column('total_return', mysql.FLOAT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('win_rate', mysql.FLOAT(), server_default=sa.text("'0'"), nullable=True, comment='胜率'),
    sa.Column('total_trades', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='总交易次数'),
    sa.Column('win_trades', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='盈利交易次数'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_virtual_accounts_user_id')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apscheduler_jobs_next_run_time'), ['next_run_time'], unique=False)

    # ### end Alembic commands ###
