"""Add win_loss trade counts to backtest result

Revision ID: 9f99af32304a
Revises: add_update_logs_table
Create Date: 2025-06-27 23:19:52.440132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f99af32304a'
down_revision = 'add_update_logs_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apscheduler_jobs_next_run_time'))

    op.drop_table('apscheduler_jobs')
    with op.batch_alter_table('backtest_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winning_trades', sa.Integer(), nullable=True, comment='盈利交易次数'))
        batch_op.add_column(sa.Column('losing_trades', sa.Integer(), nullable=True, comment='亏损交易次数'))
        batch_op.drop_column('win_trades')
        batch_op.drop_column('lose_trades')

    with op.batch_alter_table('update_logs', schema=None) as batch_op:
        batch_op.alter_column('task_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='任务名称',
               existing_nullable=False)
        batch_op.alter_column('last_update',
               existing_type=mysql.DATETIME(),
               comment='最后更新时间',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='最后更新状态',
               existing_nullable=False)
        batch_op.alter_column('message',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='最后更新消息',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_logs', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='最后更新消息',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='最后更新状态',
               existing_nullable=False)
        batch_op.alter_column('last_update',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='最后更新时间',
               existing_nullable=False)
        batch_op.alter_column('task_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='任务名称',
               existing_nullable=False)

    with op.batch_alter_table('backtest_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lose_trades', mysql.INTEGER(), autoincrement=False, nullable=True, comment='亏损交易次数'))
        batch_op.add_column(sa.Column('win_trades', mysql.INTEGER(), autoincrement=False, nullable=True, comment='盈利交易次数'))
        batch_op.drop_column('losing_trades')
        batch_op.drop_column('winning_trades')

    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apscheduler_jobs_next_run_time'), ['next_run_time'], unique=False)

    # ### end Alembic commands ###
