"""Add TopStrategyStock table

Revision ID: b9a35e2a3528
Revises: d35948171d1f
Create Date: 2025-07-02 00:49:25.119380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9a35e2a3528'
down_revision = 'd35948171d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_strategy_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False, comment='股票代码'),
    sa.Column('stock_name', sa.String(length=100), nullable=True, comment='股票名称'),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='胜率'),
    sa.Column('total_return', sa.Numeric(precision=10, scale=4), nullable=True, comment='总收益率'),
    sa.Column('annual_return', sa.Numeric(precision=10, scale=4), nullable=True, comment='年化收益率'),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=4), nullable=True, comment='最大回撤'),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True, comment='夏普比率'),
    sa.Column('backtest_result_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False, comment='在该策略中的排名'),
    sa.Column('backtest_period_days', sa.Integer(), nullable=True, comment='回测周期天数'),
    sa.Column('initial_capital', sa.Numeric(precision=15, scale=2), nullable=True, comment='初始资金'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['backtest_result_id'], ['backtest_results.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'rank', name='uk_strategy_rank')
    )
    with op.batch_alter_table('top_strategy_stocks', schema=None) as batch_op:
        batch_op.create_index('idx_strategy_rank', ['strategy_id', 'rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_top_strategy_stocks_strategy_id'), ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('top_strategy_stocks')
    # ### end Alembic commands ###
