"""Add CandidateStock table

Revision ID: d35948171d1f
Revises: 9f99af32304a
Create Date: 2025-06-28 15:13:20.415670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd35948171d1f'
down_revision = '9f99af32304a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='股票名称'),
    sa.Column('reason', sa.String(length=255), nullable=True, comment='入选原因'),
    sa.Column('added_at', sa.DateTime(), nullable=True, comment='添加时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apscheduler_jobs_next_run_time'))

    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apscheduler_jobs_next_run_time'), ['next_run_time'], unique=False)

    op.drop_table('candidate_stock')
    # ### end Alembic commands ###
